### ISSUE TITLE
Enc names

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#1]
def get_encoding_names(self):
Можно ли записать это в файл(текстом, и читать по text.splitlines)?

ошибки - turkis, englis, gree

**Comment by kvichans** [comment]
Внешний файл - ок
Ошибки. Да. Где-то последнюю букву откусил, пока перекидывал из Справки Питона

**Comment by Alexey-T** [comment]
(жду закрытия isue)

**Comment by kvichans** [comment]
fix
