### ISSUE TITLE
random()

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#10]
Если ф. даст 1 число для разных тулов- один сотрется(много запусков Куд)?

**Comment by kvichans** [comment]
да

**Comment by kvichans** [comment]
только число дается не при запуске, а при создании ВнешВыз

**Comment by Alexey-T** [comment]
можно вызывать random пока не даст Новое?

**Comment by kvichans** [comment]
todo

**Comment by kvichans** [comment]
fix
