### ISSUE TITLE
Cannot edit while run

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#100]
http://forum.ru-board.com/topic.cgi?forum=5&topic=47937&start=140#17
При выполнении например AutoIt3.exe {FileName} (из ExtTools, перехват stdout включен) , редактор недоступен до завершения программы. В SciTE например в таком же случае и редактор доступен, и stdout перехватывается

**Comment by kvichans** [comment]
Проблему понимаю. Но не знаю как подступиться к решению. Есть идеи?

**Comment by Alexey-T** [comment]
запускать тул асинхронно видимо.

**Comment by kvichans** [comment]
"асинхронно" - это цель. А как это выполнить?

**Comment by kvichans** [comment]
В браузере JS-код может использовать timer, чтобы получать управление через нужные промежутки.
А в Куд как можно сделать?

**Comment by Alexey-T** [comment]
нашел-
~~~
import threading

def hello():
    print "hello, world"

t = threading.Timer(10.0, hello)
t.start() 
~~~

**Comment by kvichans** [comment]
Да, нужно когда нибудь начинать. Ни разу еще не писал "потоки" на питоне. На Java это было обычным делом.

**Comment by Alexey-T** [comment]
Пример выше из плагина-теста не работает (hello пишет 1 раз)

**Comment by kvichans** [comment]
во! с потоками морока

**Comment by Alexey-T** [comment]
Запускаем процесс без wait (win api имеет опцию, наверно и в Пи есть опция для процесса)
И запускаем таймер по timer_proc() который ждёт конца процесса

**Comment by kvichans** [comment]
В следующей версии будет много изменений.
В частности будет опция в туле "[ ] Ожидать окончания". Если [x], то попробую блокировать Куд.

**Comment by Alexey-T** [comment]
нашел для вас пример- поиск в гугл-

This call doesn't wait for the child process to terminate (on Linux). Don't ask me what close_fds does; I wrote the code some years ago. (BTW: The documentation of subprocess.Popen is confusing, IMHO.)

proc = Popen([cmd_str], shell=True,
             stdin=None, stdout=None, stderr=None, close_fds=True)


https://stackoverflow.com/questions/3516007/run-process-and-dont-wait

**Comment by Alexey-T** [comment]
И вот примеры еще
https://stackoverflow.com/questions/1196074/how-to-start-a-background-process-in-python
