### ISSUE TITLE
btn [Set main] closes config of tool

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#102]
- run Cud
- Tools/Config
- btn Add= make new tool, select some app, i selected "test.htm"
- in empty props dlg== press [Set main]
--> all dlgs closed

**Comment by kvichans** [comment]
Не повторил. 
Что значит?: 
>in empty props dlg== press [Set main]

**Comment by Alexey-T** [comment]
В пустом диалоге "св-ва тула" нажать кнопку set main

**Comment by kvichans** [comment]
Что означает "в пустом диалоге"? Как диалог может быть пустой после выбора app?

**Comment by Alexey-T** [comment]
понял. Только если удалить конфиг exttools.json- повторяется. если есть тулы- то ок.

**Comment by kvichans** [comment]
Дык! Пустой-то нужен не диалог Св-ва тула, а диалог Список тулов.
Повторил

**Comment by kvichans** [comment]
1. Проблема в ядре Куд. Сбой происходит при пустом `items` для типа `listbox`. 
Репро: `dlg_custom('title', 210, 210, 'type=listbox\x01pos=5,5,200,200\x01items=\x01val=0')`
2. Сбой крайне неприличный - до строки после вызова `dlg_custom` управление не доходит, никакого исключения не бросается.
3. Насколько я знаю, на пустое содержимое листбокса нет запрета. Нужно только договориться, будет ли `val=0` игнорироваться или нужно придумывать аналог None для val?

**Comment by Alexey-T** [comment]
неприличный отчасти из-за плага. Вы даете itemindex=0 вне предела пустого listbox
fixed. будет проверка на индекс

**Comment by kvichans** [comment]
Да, я передаю индекс 0, который указывает на несуществующий элемент списка.
Что нужно ставить в val? Может -1 подойдет?

**Comment by kvichans** [comment]
1. Поставил -1. Fixed
2. Считаю, что изменения в ядре нужны, чтобы избежать неадекватной реакции на случайно установленный неверный индекс.

**Comment by Alexey-T** [comment]
Изменения сделал- проверки в н местах (combobox, radiogrp, listbox etc)
