### ISSUE TITLE
Tidy cannot work, pls test

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#106]
Почему то Tidy не работает

![tool-win](https://cloud.githubusercontent.com/assets/4154978/26638377/a38a6b44-462a-11e7-9bcf-9b5477ddec55.png)

![cannot](https://cloud.githubusercontent.com/assets/4154978/26638397/adfe2228-462a-11e7-8907-67bf9bf814c4.png)

**Comment by kvichans** [comment]
У меня работает

**Comment by kvichans** [comment]
У вас что-то ОС-зависимое, судя по строке
`Error: Can't open " /home/user/test.htm"` 

1. Странно смотрится пробел перед /home
2. Похоже tidy не поделил файл с Куд

Пробовали запустить tidy из терминала? Подозреваю, он то же самое скажет

**Comment by Alexey-T** [comment]
Опс, это пробел виноват
