### ISSUE TITLE
Deprecated callback

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#107]
Deprecated API callback, report to plugin author: cuda_exttools,dlg_config

**Comment by kvichans** [comment]
Как поймать где это?

**Comment by Alexey-T** [comment]
Кликнуть все  пункты в Tools>...

**Comment by kvichans** [comment]
Не понял

**Comment by Alexey-T** [comment]
при вызове Tools> Config, после диалога,
я вижу в консоли
Deprecated API callback, report to plugin author: cuda_exttools,dlg_config

**Comment by kvichans** [comment]
Получил только такое
*Bad API callback, report to plugin author: _cuda_exttools:adapt_menu_*
Не могу понять, где править.
Откуда приходит это сообщение?

**Comment by Alexey-T** [comment]
Я поищу в вашем ГХ

**Comment by Alexey-T** [comment]
нашел cd_exttools.py
`
        pass;                  #LOG and log('id_menu={}',id_menu)
PLUG_HINT = '_'+'cuda_exttools:adapt_menu' # "_" is sign for ConfigMenu. ":" is subst for "," to avoid call "import ..."`

**Comment by kvichans** [comment]
Ага. Начинаю понимать
Проблема в недостаточности параметров в АПИ
`menu_proc(id_menu, id_action, command="", caption="", index=-1)`
Как через эти параметры мне занести информацию в `hint`?!
Раньше я для этого использовал поле cmd.

**Comment by Alexey-T** [comment]
кажется надо дать command='cuda_exttools.adapt_menu' .
оно запишет hint.

**Comment by kvichans** [comment]
Я пользовался тем, что для ПОДМЕНЮ поле cmd вообще не должно использоваться - и хранил в нем данные для связи.
Почему hint нельзя задать из АПИ?

**Comment by Alexey-T** [comment]
Это не было нужно -hint хранит что вы даете в command

**Comment by kvichans** [comment]
Фактически мне опять не хватает tag! То есть дайте возможность хранить нужные мне, а не ядру данные

**Comment by Alexey-T** [comment]
подумаю, как хранить таг в TMenuItem.

**Comment by kvichans** [comment]
>Это не было нужно -hint хранит что вы даете в command

Вот это я и делаю. А вы пытаетесь их вызывать на исполнение

**Comment by Alexey-T** [comment]
да, любая строка там дает исполнение. кроме int(n)

**Comment by kvichans** [comment]
К слову. Перевел все вызовы тулов из меню на живые ссылки - красота!

**Comment by kvichans** [comment]
>да, любая строка там дает исполнение. кроме int(n)

Дык! Ясно, это же поле для команды. Раньше "невызывалось" и ок. А теперь критика в консоль попадает

**Comment by Alexey-T** [comment]
Можно tag= отложить на 1.10.1?
пока у меня 1.10

**Comment by kvichans** [comment]
Да, будет просто часто видно "Bad callback" - но работать будет нормально

**Comment by Alexey-T** [comment]
сообщения уже нет. решено?

**Comment by Alexey-T** [comment]
вроде решено
