### ISSUE TITLE
Hotkeys in menu

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_exttools#108]
Сейчас удается показать хоткеи для тулов в меню вот так
![hotkeys in tools](https://user-images.githubusercontent.com/7419630/27231866-b9602b2c-52bc-11e7-98a9-0f71372156ab.png)
Лучше чем ничего. Но это конечно коряво.
- Так будет всегда? 
- Можно ли добавить к АПИ для меню эту подсказку?
- Может ли ядро само ее получить? Плагин-то может

**Comment by Alexey-T** [comment]
Menu_proc() кажется умеет задать хоткей, нет?

**Comment by kvichans** [comment]
сейчас норм
