### ISSUE TITLE
Use new callbacks from ConfigToolbar buttons

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#109]
@kvichans
Плаг ConfigToolbar дает в кнопку такой колбек

    module=..;cmd=..;info=..;

Теперь кнопка вызывает тулы.
Например "firefox.exe".
Тулы ругаются на параметр info

Надо чтобы тулы понимали вызов таким колбеком.

**Comment by kvichans** [comment]
Опять те же грабли!
Вы опять совместили тот info, с помощью которого мы живые ссылки организуем в cudatext.py, и какое-то новое его применение.

Как можно будет вызывать живую ссылку из тулбара?

**Comment by kvichans** [comment]
Поскольку вся кухня с организацией живых ссылок начинается и заканчивается внутри cudatext.py **нужно** перестать для этого использовать _публичные_ параметры API. Ничего не мешает добавить _технический_ параметр, только для этой цели.

**Comment by kvichans** [comment]
Рассмотрел (с этого мне нужно было начинать, винюсь)
```python
def _menu_proc_callback_proxy(info=''):
    if info in _live:
        _live[info]()
def toolbar_proc(id_toolbar, id_action, text="", text2="", command=0, index=-1, index2=-1):
    if callable(command):
        sid_callback = str(command)
        _live[sid_callback] = command
        command = 'module={};func=_menu_proc_callback_proxy;info="{}";'.format(__name__, sid_callback)
    return ct.toolbar_proc(str(id_toolbar), id_action, text, text2, str(command), index, index2)
```
Не понял, где не хватает параметра `info`. Вижу только `_live[info]()` - это вызов живой ссылки из тулбара без параметров. В чем проблема?

**Comment by Alexey-T** [comment]
подумаю.
Проблема без ж-ссылок. с обычными ссылками

**Comment by kvichans** [comment]
Не понимаю:
>Теперь кнопка вызывает тулы.
> Например "firefox.exe"

Как вы указали тул для кнопки? Речь про тул из плагина cuda_exttools? Я не предоставлял никакого API для внешнего вызова этих тулов. Единственный метод из Command `def run(self, ext_id)` позволяет запустить тул. Но ему нужно подавать корректный id.

**Comment by Alexey-T** [comment]
Я вызвал выбор команды в плагине и набрал firef и выбрал тул из всех команд

**Comment by kvichans** [comment]
"выбор в плагине"? каком?

**Comment by Alexey-T** [comment]
Выбор команды в config toolbar вызывает dlg_commands

**Comment by kvichans** [comment]
Получается кривое назначение. Нельзя вызывать тулы! Нет у них такого свойства

**Comment by Alexey-T** [comment]
Значит мой ляп

**Comment by kvichans** [comment]
Поставил плагин.
**Я оказался не прав**. Плагин берет вызов из "регистрации" тула в ядре.
Этот вызов содержит правильный id

Теперь опять возвращаемся к вопросу: где тут info?

**Comment by kvichans** [comment]
(Что-то не везет мне с этой темой - все время торможу)
Вижу, что ваш плагин команду сделал такую
module=cuda_exttools;cmd=run;info=333982;
А регистрировал я ее так
app_proc(PROC_SET_SUBCOMMANDS, "cuda_exttools;run;333982")
Рассчитывая (и ведь это происходит!), что ядро будет вызывать
cuda_exttools.run(333982)

Почему вы настаиваите на info?

**Comment by kvichans** [comment]
Сейчас у run параметр позиционный. Я не против сделать его именованным.

**Comment by kvichans** [comment]
Тестируйте

**Comment by Alexey-T** [comment]
"Стало хорошо"
