### ISSUE TITLE
No run if empty filename

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#11]
If tab untitled: don't run tool if has macros {FileNNNNNNN}- show status message "Cannot run this tool for untitled tab"

**Comment by kvichans** [comment]
Не точно
Так _можно_ делать только, если в ВнешВыз не стоит "сохранять перед выполнением"

Кстати, эти и к реализации exttool (ко мне относится)

**Comment by Alexey-T** [comment]
стоит опция или нет- если вы при запуске видите get_filename empty (юзер отменил save)- надо msg.

**Comment by kvichans** [comment]
зачем msg? достаточно просто не запускать на выполнение - ведь пользователь **уже** нажал Отменить

**Comment by kvichans** [comment]
Я так и буду делать

**Comment by Alexey-T** [comment]
Сбщ для untutled tabs которые не сейвили

**Comment by kvichans** [comment]
"буду"!
