### ISSUE TITLE
ru-board bug in Cud 1.12

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#111]
http://forum.ru-board.com/topic.cgi?forum=5&topic=47937&start=300#7

**Comment by kvichans** [comment]
Как узнать какие версии API с каким выпусками Куд?
В плагине стоит отсечка по версии АПИ 1.0.187 - а какая это сборка Куд?

**Comment by Alexey-T** [comment]
узнать-
Скачать, запустить, ввести =app_api_version()

**Comment by kvichans** [comment]
Это не серьезно! Я не представляю, как скачать прежнюю версию Куд.

**Comment by Alexey-T** [comment]
это решено?
