### ISSUE TITLE
Parse out lines like Synw

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#12]
Synwrite ExtTools имеет фичу "как разбирать вывод тул"- есть опц.
- regex
- index of fname
- index of line/col

по regex Син разбирает лог и подсвечивает output
wish. Так же в Cud ExtTools.
Через app_log можно давать regex, index of fname/ line/ col

**Comment by kvichans** [comment]
Тоже  репозиторием ошиблись?

**Comment by Alexey-T** [comment]
wish for Cud Exttools. Пост поправил

**Comment by kvichans** [comment]
Да, шаблоны для тулов будут позже

**Comment by Alexey-T** [comment]
Ok
