### ISSUE TITLE
2 monitors on Linux, dlg pos not saved

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#124]
Linux, gtk2, 2 монитора. второй - слева.
Вызвали плагин длг (Список тулов) - ставим длг на монитор правый.
Вышли, зашли в длг еще раз - длг на правом монике - ОК.
Заходим в правку любого тула.

Баги:
1- Длг "Св-ва тула" все время - на левом мониторе хотя я его тащил на правый.
2- После ОК в "Св-ва тула" - список тулов открылся на ЛЕВОМ монике хотя я уже его таскал на правый.

**Comment by kvichans** [comment]
Хорошая заковыка.
1. Сейчас диалог Св-ва тула работает через dlg_custom.  У меня нет способа управлять местом его отображения - могу только размеры задать. Значит проблема в ядре.
2. А что с ФИФ - он запоминает монитор? Скорее всего нет. ФИФ работает через dlg_proc и может сохранять/задавать положение диалога. Но я не знаю способа задать монитор. Поясните

**Comment by Alexey-T** [comment]
Задать монитор это задать прошлую позицию. По позишн задастся и монитор. Координаты Моников Апи даёт так- proc_coord_monitor0....3

**Comment by kvichans** [comment]
Что с ФИФ?

**Comment by kvichans** [comment]
Если несколько мониторов, то они лежат в общем координатном пространстве? 
Тогда ФИФ уже должен запоминать положение, а Тул будет, когда переведу на dlg_proc

**Comment by Alexey-T** [comment]
Да, в общем прос-ве 
Поправить баг 2 вы можете уже сейчас

**Comment by kvichans** [comment]
> Поправить баг 2 вы можете уже сейчас

Как?

**Comment by Alexey-T** [comment]
Диалог Список тулов открылся не там. Дадите ему позицию от прошлого вызова

**Comment by kvichans** [comment]
Где в 
`dlg_custom(title, size_x, size_y, text, focused=-1, get_dict=False)`
задание позиции диалога?

**Comment by Alexey-T** [comment]
Список тулов у вас тоже dlg_custom? тогда вопрос закрыт
