### ISSUE TITLE
strange line in cd_exttools.py

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#129]
l=chr(13)
зачем эта переменная?

**Comment by kvichans** [comment]
Чистый рудимент от тех времен, когда мне было удобно добавлять EOL к строке в виде
sData+l

**Comment by Alexey-T** [comment]
Закроете когда удалите

**Comment by kvichans** [comment]
Вам это зачем?
Это лишь одно из проявлений *моего стиля*, который весьма отличается от PEP-8
