### ISSUE TITLE
Tool output is inserted into selection without terminating CrLf

### ISSUE THREAD

**Issue by dinkumoil** [kvichans/cuda_exttools#135]
# Description

When in `Tool properties -> Capture output -> Replace selection` is choosen, tool output is inserted without terminating CrLf. This causes the first line following the selected line(s) in the document to be "glued" together with the last output line of the called tool.

# Fix

I was able to fix that issue with the following small extension:

![grafik](https://user-images.githubusercontent.com/24699812/58358947-5a289200-7e81-11e9-960d-8d0f3ebcdcf8.png)

This is the original code from the repo:

![grafik](https://user-images.githubusercontent.com/24699812/58358965-6b719e80-7e81-11e9-80c9-426f808cf535.png)

# Applies to

Version 1.2.35 2019-03-26

**Comment by kvichans** [comment]
I see a nuance for the subj.
I never used _Capture output_ as _Replace selection_ (moreover never tested the option - sorry), but i can imagine two situations:
1. Some source lines will be replaced with some output lines (as in your wish)
2. Inline source fragment will be replaced with new fragment 

Current plug way is good only for the second. After your fix - only for the firsrt.

Lets to analyze source selection (each part) and output data:
- If the selection has EOL then the output not stripped
- If the output has more then one line then the output not stripped
- Otherwize the output will be stripped (to inline replacement)

Is it good?

**Comment by dinkumoil** [comment]
Good point, I forgot to consider your case 2.

But why "If the output has more than one line then the output not stripped"? I think "If the selection has (terminating) EOL then the output not stripped" is sufficient. It could be that the selection is one and a half line (no terminating EOL), in that case a terminating EOL in tool's output should be stripped.

**Comment by kvichans** [comment]
OK
Plug will analyze only selection (each part). If selection ends with EOL or next char is EOL/EOF then output will be not stripped before insertion.

**Comment by kvichans** [comment]
fixed and published

**Comment by dinkumoil** [comment]
Hmm, where?

**Comment by kvichans** [comment]
![изображение](https://user-images.githubusercontent.com/7419630/58497138-f9040580-8183-11e9-846d-bdb3a5bee448.png)

**Comment by dinkumoil** [comment]
Perfect, works like a charm. Thank you!
