### ISSUE TITLE
Error "TypeError: 'NoneType' object is not iterable" when captured tool output should replace selection

### ISSUE THREAD

**Issue by dinkumoil** [kvichans/cuda_exttools#136]
# Description

When in `Tool properties -> Capture output -> Replace selection` is choosen, the plugin fails with the error message `TypeError: 'NoneType' object is not iterable`.

# Fix

I was able to fix that issue with the following small change:

![grafik](https://user-images.githubusercontent.com/24699812/58359213-9c9e9e80-7e82-11e9-845d-5137b77f2125.png)

This is the original code from the repo:

![grafik](https://user-images.githubusercontent.com/24699812/58359221-a6c09d00-7e82-11e9-8779-cbde4b08abf8.png)

# Applies to

Version 1.2.35 2019-03-26

**Comment by Alexey-T** [comment]
```
>>> list(reversed([2,3,5]))
[5, 3, 2]
```

**Comment by dinkumoil** [comment]
@Alexey-T 

I don't understand.

The reason for the error is that the `reverse` method of lists doesn't return a value, it just reverses its list in-place. Thus the original code couldn't work, the `for` loop has no list to work with.

**Comment by Alexey-T** [comment]
It was a tip for @kvichans, how to fix his code...

**Comment by kvichans** [comment]
@dinkumoil Thanks. Good fix.
