### ISSUE TITLE
Plugin runs configured tool only two times

### ISSUE THREAD

**Issue by dinkumoil** [kvichans/cuda_exttools#138]
# Steps to reproduce

1. Download and unpack a fresh copy of _CudaText_ for Windows (I have tested it with v1.98.0 x64 on Windows 7 x64).
2. Install plugin _ExtTools_.
3. Create a batch script named `RunScript.cmd` and store it under `<CudaText-folder>\exttools\CodeLauncher`. Copy the following code to this file:
```
@echo off & setlocal


:: =============================================================================
:: Guard
:: =============================================================================
if "%~1" equ "" exit /b 1
if not exist "%~1" exit /b 2


:: =============================================================================
:: Dispatcher
:: =============================================================================
set "FileNameExt=%~x1"
cd /d "%~dp1"

if /i "%FileNameExt%" equ ".bat" (
  call :RunBatchScript "%~1"

) else if /i "%FileNameExt%" equ ".cmd" (
  call :RunBatchScript "%~1"

) else (
  call :FileTypeNotSupported
)

exit /b 0


:: =============================================================================
:: Language specific handlers
:: =============================================================================

:: -----------------------------------------------------------------------------
:: Batch Script
:: -----------------------------------------------------------------------------
:RunBatchScript
  call "%~1"
  pause
exit /b 0


:: -----------------------------------------------------------------------------
:: Unsupported file types
:: -----------------------------------------------------------------------------
:FileTypeNotSupported
  echo This language is not supported.
  echo(
  pause
exit /b 0
```
4. Create a tool with the following configuration but change the `Encoding` setting to your local needs. **Please note:** This configuration is for starting a 32 bit console on a 64 bit Windows OS, that's the reason for the `C:\Windows\SysWOW64\cmd.exe` path.

![grafik](https://user-images.githubusercontent.com/24699812/80495477-42e30600-8968-11ea-91a3-e5f22a8b76de.png)

5. Create a batch script named `test.cmd` in an arbitrary folder with the folllowing content:
```
dir c:\*.*
```
6. Load file `test.cmd` into _CudaText_.

**Please note:** During the following sequence always wait until the message field in the status bar of the _CudaText_ window that informs about tool execution has been cleared before advancing to the next step.

1. Press configured keyboard shortcut `Ctrl+F9`.
2. The script `test.cmd` starts in a console window. Press any key to close the console.
3. Press configured keyboard shortcut `Ctrl+F9`.
4. The script `test.cmd` starts in a console window. Press any key to close the console.
5. Press configured keyboard shortcut `Ctrl+F9`.
6. Ths script doesn't start. Instead the status bar of _CudaText_ window shows a message `No tool:`

From this point on, pressing the configured keyboard shortcut is not succesfull anymore. The message field of the status bar displays random text instead. Sometimes it's the content of other status bar fields, for example the tabulator info or the line/column info. Additionally the tabulator info field's content gets garbled.

After pressing the shortcut some times, the sequence always ends with displaying `No tool: xxcuda_exttools`.

**Comment by kvichans** [comment]
@dinkumoil Pls zip and post here files:
CudaText\settings\exttools.json
RunScript.cmd
test.cmd

**Comment by dinkumoil** [comment]
ZIP file: [ExTools_Issue#138.zip](https://github.com/kvichans/cuda_exttools/files/4546705/ExTools_Issue.138.zip)

You can unzip it in _CudaText_ folder, all files will be at their correct location.

**Comment by kvichans** [comment]
@dinkumoil Pls repro steps and post here Console content

**Comment by dinkumoil** [comment]
@kvichans For repro steps see my initial posting, should be detailed enough...

_CudaText_ console content after three failed attempts to start the tool:

![grafik](https://user-images.githubusercontent.com/24699812/80514664-1a1b3a80-8981-11ea-97d4-3ebdf28107fd.png)

**Comment by dinkumoil** [comment]
@kvichans 

I want to explicitely hint you to the fact, that the error sequence from my console screenshot above is **reproducible if** you always wait until the message field in the _CudaText_ statusbar is cleared.

If you do **not** wait, you will get an other, more random error sequence. Even the exception may not occur in this case.

**Comment by Alexey-T** [comment]
CudaText api has fail if plugin passes str with Null chars to it. here it is the case. ExtTools plugin must work around it, delete null chars.

**Comment by Alexey-T** [comment]
making wrapper for some Pas function to solve it:
```
procedure _DecodePyZero(var s: string);
begin
  if Pos('\', s)>0 then
  begin
    s:= StringReplace(s, '\0', #0, [rfReplaceAll]);
    s:= StringReplace(s, '\\', '\', [rfReplaceAll]);
  end;
end;
```
@kvichans

**Comment by Alexey-T** [comment]
@dinkumoil Pls test on new release win32/win64 1.98.1

**Comment by dinkumoil** [comment]
AFAIK it works, thank you!

@kvichans  Because @Alexey-T wrote in his commit message that it is a temporary solution I keep this issue open.

**Comment by dinkumoil** [comment]
@Alexey-T  @kvichans 

Unfortunately the issue is not gone, tested with _CudaText_ v1.98.2 x64 on Windows 7 x64.

**I should explicitely tell you, that the plugin only fails to execute a tool if the hot key was used to start it. Starting the tool via its menu entry works fine.**

In the following some more screen shots of the _CudaText_ console that show different error sequences. **Please note:** Between the tests I restarted _CudaText_.

1. This error sequence happened when I pressed the tool's hot key and **always waited** until the message field in the status bar of _CudaText_ has been cleared. The first two times the tool's execution worked, the next 5 attempts failed:

![grafik](https://user-images.githubusercontent.com/24699812/80809774-aa948d80-8bc2-11ea-8551-499f1a778298.png)

2. This error sequence happened when I pressed the tool's hot key and did **not wait** until the message field in the status bar of _CudaText_ has been cleared. Again the first two times tool's execution worked, the 3rd and 4th attempts failed. **This screen shot also includes the _CudaText_ status bar:**

![grafik](https://user-images.githubusercontent.com/24699812/80811002-5343ec80-8bc5-11ea-93b7-0b788a5e06e1.png)

**Comment by dinkumoil** [comment]
New ZIP file with all files for testing. This time file _keys.json_ is included too, thus hot key _Ctrl+F9_ works out-of-the-box.

[ExTools_Issue.138.zip](https://github.com/kvichans/cuda_exttools/files/4564693/ExTools_Issue.138.zip)

**Comment by dinkumoil** [comment]
@kvichans @Alexey-T 

Can you confirm this issue?

**Comment by Alexey-T** [comment]
on Linux hotkey works 5+ times, on wine:
![Screenshot from 2020-05-11 16-20-52](https://user-images.githubusercontent.com/4154978/81566608-c73f7b00-93a3-11ea-82f6-c0925fc4f863.png)

changed "catch output" option.

**Comment by Alexey-T** [comment]
on Win10 I don't confirm it - I pressed ctrl+F9 10 times, and got all times Cmd window with the message "this language is not supported. Press any key to continue..."

Cud 1.98.5 win64 beta

**Comment by dinkumoil** [comment]
At the moment I can confirm that the issue is gone, tested under Windows 7 x64 with CudaText v1.98.5.0 x64. But let's wait a while before closing this issue. Some days ago I thought it would have been fixed as well...

**Comment by dinkumoil** [comment]
Seems to be fixed.
