### ISSUE TITLE
Tool Properties don't support tool name with ~

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#139]
tool

![Screenshot from 2020-07-12 23-05-01](https://user-images.githubusercontent.com/4154978/87255522-3749aa80-c494-11ea-8128-5271a3402d28.png)

gives error
![Screenshot from 2020-07-12 23-04-41](https://user-images.githubusercontent.com/4154978/87255524-3e70b880-c494-11ea-889f-816a4c2cc2fd.png)

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Try from GH

**Comment by Alexey-T** [comment]
Нет, нельзя делать просто replace - Тильда в середине это не хоум, Тильда в ~dd/dd тоже

**Comment by kvichans** [comment]
Как сделать правильную замену?

**Comment by Alexey-T** [comment]
делаю пач.
