### ISSUE TITLE
(ask) How set around frame?

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_exttools#14]
Можно ли из текущих контролов dlg_custom сделать _рамку для с подписью_ для обозначения именованной группы, которую она будет окружать?
Похоже что ответ "нет"

**Comment by Alexey-T** [comment]
Нет- группа требует контролов НА ней, и пришлось бы делать parent= парам-р

**Comment by kvichans** [comment]
Правильно я понимаю, что в коллекции доступных контролов (в Лазарус) нет рамки с подписью? Это ведь аналог label

**Comment by Alexey-T** [comment]
есть. groupbox. 
(это не рамка а контейнер. надо делать контролам ссылку на нее)

**Comment by kvichans** [comment]
Получиться затянуть его в Куд?

**Comment by Alexey-T** [comment]
Контролам надо давать поле parent= что криво

**Comment by kvichans** [comment]
Зачем?

**Comment by kvichans** [comment]
А простая рамка (rectangle) есть? Можно из нее И из label сделать

**Comment by Alexey-T** [comment]
чтобы контрол был в рамке ему надо давать (Лаз) св-во parent=<groupbox>

**Comment by kvichans** [comment]
Зачем!? Почему нельзя просто положить рамку на форму, а потом сверху разместить контролы?
Пользователю безразлично, как получена картинка

**Comment by kvichans** [comment]
В Лазарусе есть простые контролы: круг, прямоугольник ?

**Comment by Alexey-T** [comment]
Как эск-т сделаю группу groupbox без парентов
Круг- прямоуг-к есть

**Comment by kvichans** [comment]
Дайте прямоугольник с внутренним цветом как вокруг и черной рамкой
Я наложу на его рамку label - получится то что нужно

**Comment by kvichans** [comment]
А-а-а! Мне не нужна группа!
Мне нужно **визуально** отделить часть контролов

**Comment by Alexey-T** [comment]
дам контрол group-В бете потом

**Comment by kvichans** [comment]
Изящный получился контрол.

Нужно его включить в технологию ускорителей. Сейчас 
type=group
cap=&Tools
показывает подчеркивание, но перехода по Alt+T на следующий контрол (у меня это listbox)
не происходит

**Comment by Alexey-T** [comment]
для "группы" такого не надо- так не делают в UI

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
..можно закрыть

**Comment by kvichans** [comment]
Если доделаете, то будет хорошо
Если нет - можно закрыть

**Comment by Alexey-T** [comment]
закройте...
