### ISSUE TITLE
navigation in Output panel broken after deleting work of 'tag' in app_log()

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#144]
1)
```
            elif rslt in (RSLT_OP, RSLT_OPA):
                app.app_log(app.LOG_ADD, out_ln, crc_tag, panel=app.LOG_PANEL_OUTPUT)
```
здесь задавали тег

2)
здесь его читали
```
       ext_pttn    = ext['pttn']
        op_line_tags=app.app_log(app.LOG_GET_LINES_LIST, '', panel=app.LOG_PANEL_OUTPUT)
        pass;                  #LOG and log('op_line_tags={}',op_line_tags)
#       op_line_tags=app.app_log(app.LOG_GET_LINES, '', panel=app.LOG_PANEL_OUTPUT)
#       pass;                   LOG and log('op_line_tags={}',op_line_tags)
#       op_line_tags=[(item.split(c13)[0], int(item.split(c13)[1])) 
#                       if c13 in item else 
#                     (item, 0)
#                       for item in op_line_tags.split(c10)]
#       pass;                   LOG and log('op_line_tags={}',op_line_tags)
        for op_ind in (range(self.last_op_ind+1, len(op_line_tags)) 
                        if what=='next' else
                       range(self.last_op_ind-1, -1, -1) 
                      ):
            line, crc   = op_line_tags[op_ind]
            if crc != self.last_crc:            continue    #for
            if not re.search(ext_pttn, line):   continue    #for
            self.last_op_ind = op_ind
            app.app_log(app. LOG_SET_LINEINDEX, str(op_ind), panel=app.LOG_PANEL_OUTPUT)
            self.on_output_nav(ed, line, crc)
            break   #for
        else:#for
            app.msg_status(_('No more results for navigation'))
```

предлагаю давать в панель output некую сигнатуру (например первая строка 'External Tool output') и определять что вывод ваш, через наличие сигнатуры.

**Comment by Alexey-T** [comment]
@kvichans bump

**Comment by SerzhSmith** [comment]
По ошибкам так и не прыгает, **cd_exttools.py:673** forever.  Для себя из желудей и спичек соорудил это:

![exttools](https://user-images.githubusercontent.com/42665999/126185136-eb7324d7-4ecf-4140-b507-1846a9714617.jpg)

Но, думаю, профессиональное решение было бы лучше.

**Comment by Alexey-T** [comment]
Я начал делать правку но запутался .... смысл такой. Заводим словарь в котором содержим маппинг между «строка из вывода» и словариком с инфой про эту строку вывода. Не нужно уточнить - из какого именно Тула и какого файла эта строка. Например строка

path/main.c:20 - error here 

однозначно смаппится на словарик с инфой- какой файл, какой номер строки (это парсится из строки вывода), какой тул.

Потом при клике в панели вывода- по строке вывода- получаем все.
@kvichans 

правда может быть строка без filepath , тогда мы будем путать ее среди всех файлов main.c - но это терпимо.

**Comment by Alexey-T** [comment]
@SerzhSmith Пока автор занят, и советую попробовать второй плагин
https://wiki.freepascal.org/CudaText_plugins#Runner

**Comment by SerzhSmith** [comment]
**@Alexey-T** Спасибо, обязательно попробую.
Также спасибо за классный редактор.

**Comment by halfbrained** [comment]
> Заводим словарь в котором содержим маппинг между «строка из вывода» и словариком с инфой про эту строку вывода. Не нужно уточнить - из какого именно Тула и какого файла эта строка.

@Alexey-T Наверное лучше не сканировать каждую строку сразу, output может же быть и немаленький.
Может лучше словарь: хэш строки -> инфо о туле?

**Comment by Alexey-T** [comment]
Может быть и так.

**Comment by halfbrained** [comment]
Команды `Next/Previous tool result` -- если я правильно понимаю -- ищут tool regex pattern в последлем output запуска тула. -- Не то что я ожидал, так задумано? :)

Эти команды использую удаленный `tag`, и я думаю как переделать... оставить как было?

**Comment by Alexey-T** [comment]
как это оставить как было? они же не работают правильно, когда у нас например есть два таба с двумя разными лексами и два тула исп-ются.

**Comment by halfbrained** [comment]
Я привязываю инфу о запуске тула к хэшу каждой строки из output, у меня будет вся таже информация как и с тэгами было - проблемы быть не должно... Или я что-то упустил?

**Comment by Alexey-T** [comment]
тогда вроде бы все Окей.

**Comment by halfbrained** [comment]
Должно работать почти как раньше.

**Comment by Alexey-T** [comment]
@SerzhSmith  @kvichans 
пож-та, попробуйте форк плагина на 
https://github.com/halfbrained/cuda_exttools
стало ли нормально с навигацией?

**Comment by SerzhSmith** [comment]
**@Alexey-T**, **@halfbrained**, спасибо, да, отлично работает.
