### ISSUE TITLE
err- "save before"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#18]
File "/home/user/cuda/cuda/app/py/cuda_exttools/cd_exttools.py", line 504, in run
    if not ed.file_save():  return
AttributeError: 'Editor' object has no attribute 'file_save'

**Comment by kvichans** [comment]
Fix
Это из-за _неестественности_ API : 
- Сохранить **все** вкладки вызывается от ed
- Сохранить **текущую** вкладку вызывается от приложения

**Comment by Alexey-T** [comment]
ed.save тоже сейвит текущую...
