### ISSUE TITLE
err- clone buttn

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#20]
выбрал второй тул- на моем скрине- "edit"
жму clone- 
bug- диалог пропал, 
bug- появился в меню третий тул НО в списке потом опять 2

wish--клонировать в имя "edit и-чтото"

**Comment by Alexey-T** [comment]
```
Command.dlg_config:133 exkys=['Tidy [Ctrl+T]', 'edit', '', 'edit']
```

**Comment by kvichans** [comment]
> wish--клонировать в имя "edit и-чтото"

ок
Буду добавлять _что-то_, чтобы имена различались

**Comment by Alexey-T** [comment]
жму clone-
bug- диалог пропал,
bug- появился в меню третий тул НО в списке потом опять 2

**Comment by kvichans** [comment]
"bug- диалог пропал"
А каретка в списке стоит на туле?

**Comment by Alexey-T** [comment]
да

**Comment by kvichans** [comment]
Чтобы диалог не пропадал, сделал заполнение пустых имен
fix
