### ISSUE TITLE
Empty items in extlist

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#22]
Как получить чудесный список

```
Command.dlg_config:133 exkys=['Tidy [Ctrl+T]', '', 'edit', '', '']
```

делаем add, в длг файла делаем отмену.

**Comment by kvichans** [comment]
Что _чудесного_ в списке? Просто было создано несколько тулов без имен
"в длг файла делаем отмену" - это как?

**Comment by Alexey-T** [comment]
То что пустой п. в спискк прерывает чтение listbox- надо давать в listbox пробел (не пусто)

**Comment by Alexey-T** [comment]
в диалоге dlg_file - Отмена

**Comment by kvichans** [comment]
fix (уже выложил)

**Comment by kvichans** [comment]
Про "надо давать в listbox пробел" не знал - учту
