### ISSUE TITLE
(bug) Cannot call hotkeys for plugin after lexer props are updated

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_exttools#23]
Стабильно натыкаюсь, что после обновления библ.лексеров не работают сочетания для плагинов, пока не перевызовешь Куд.
Что это?

**Comment by Alexey-T** [comment]
плс, issue у меня

**Comment by kvichans** [comment]
сори, опять не в тот репозиторий добавил

**Comment by Alexey-T** [comment]
fix

**Comment by Alexey-T** [comment]
закройте?
