### ISSUE TITLE
(bug) Process done

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#30]
подозрение. не точно. Может не закрываете процесс. запустил tidy 2-3 раза- менял shell=on/off- tidy стал игнорить файл- даже если вернул shell=off -все равно все запуски "не видят файл"

**Comment by kvichans** [comment]
"не закрываете"? Его еще и закрывать нужно? Сам он не умирает?

**Comment by Alexey-T** [comment]
надо см-ть subprocess. может надо закрывать? (после перезапуска К стало норм.)

**Comment by kvichans** [comment]
Буду рад помощи. В этой области я профан

**Comment by Alexey-T** [comment]
я не знаю это.

**Comment by Alexey-T** [comment]
вы не повторяете проблему, если вкл, выкл, вкл, выкл shell= для Tidy? tidy output "Output panel"
