### ISSUE TITLE
{Filename}

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#34]
wish.Если парам-р имеет {Filename},то давать ош при запуске тула,при untitled tab.

**Comment by kvichans** [comment]
Сейчас идет запрос на сохранение. Если пользователь Отмену жмет, то тул не выполняется.
Не нужно запрос делать?

**Comment by Alexey-T** [comment]
не стоит опц "сохранять".Значит запрос не надо.
