### ISSUE TITLE
Sel index

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#36]
диалог открывается, listview index не задан, в Вин нет синей полосы на listview, wish- задавать index.

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
У меня на Win у листбокса выделение имеет три состояния
- нет совсем
- есть, но виден только контур
- есть и закрашен фон 

Сделал умолчательный индекс, но смог только второй вариант выделения использовать

**Comment by Alexey-T** [comment]
это нормально
