### ISSUE TITLE
(feature) New format for Tool pattern

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_exttools#38]
Оказывается в re у Питона есть именованные группы!
Я сделаю через них.
Сравните:
- В Син разбор ошибки при запуске Питона делается при указании
  - рег.выр: `\w+ "(.+)", line (\d+).*`
  - номера группы с _именем файла_: **1**
  - номера группы с _строкой_: **2**
  - номера группы с _колонкой_: **--**
- Куд это будет делаться **одним** рег.выражением
  
  `\w+ "(?P<file>.+)", line (?P<line>\d+).*`

Нужно передать в плагин навигацию по строкам из Output

**Comment by Alexey-T** [comment]
Да-согласен..

**Comment by kvichans** [comment]
Будет `on_output_nav`?

**Comment by Alexey-T** [comment]
- html tidy вывело строки
- я делаю дб клик
- как вы узнаете что это вывод НЕ ваш

**Comment by kvichans** [comment]
tidy запущен как tool?

**Comment by Alexey-T** [comment]
(плагин tidy, а не тул)

**Comment by kvichans** [comment]
А как вы сейчас различали бы, после того как я передал через app_log шаблон и номера групп к нему?

**Comment by Alexey-T** [comment]
никак
Надо метить строки "от кого они пришли" мне

**Comment by kvichans** [comment]
да, нужно в `on_output_nav` подавать кто заполнял
если не указано, то я буду считать, что последний запущенный tool

**Comment by kvichans** [comment]
если сможете про каждую строку помнить _заполнителя_, то проблемы не будет совсем

**Comment by kvichans** [comment]
Из текстовых полей тула собрал строку. 
Из нее сделал crc32 (взял часть битов, чтобы формат подходил под знаковый int32). 
Это число передаю при выдаче в output.
При анализе строки из output по этому числу определяю, какой тул строку генерил.

Работает.

**Comment by Alexey-T** [comment]
хм, у хеш могут быть коллизии (лучше без crc32).

**Comment by kvichans** [comment]
Коллизии для 20-30 тулов при генерации миллиарда целых - не верю!
CRC не хранятся, а заполняются при каждом вызове. Можно расслабиться

**Comment by Alexey-T** [comment]
Вероятность 30/милиард
