### ISSUE TITLE
name of button

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#39]
предл. назваить кнопы справа
- browse-> file
- add-> param
- browse-> folder
- lexers
- main tool
- hotkey
- encoding
- pattern

**Comment by kvichans** [comment]
Делал, глядя на Син
Посмотрю, что из предложенного пригодится

**Comment by kvichans** [comment]
Ваше предложение плохое - на кнопки лучше ставить глаголы, а не существительные.
Каждая из кнопок стоит третьей в ряду
-  Имя свойства, значение свойства, действие для изменения значения

_Действие_ требует глагола
