### ISSUE TITLE
Run refac

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#4]
Можно сделать **все про запуск(но не про обращение к списку exts, не обращение к json)в новый файл?

**Comment by kvichans** [comment]
не понял

**Comment by Alexey-T** [comment]
сделать ф-ции (обертки) работы с процессами. process.Popen юзать только в них. вынести их в модуль.

**Comment by kvichans** [comment]
Какой смысл?

**Comment by Alexey-T** [comment]
Править код с процессами -легче, не трогать init.py

**Comment by kvichans** [comment]
Вот дожмем cudatext_reset_plugins.py и вынесу

**Comment by Alexey-T** [comment]
"жду"
