### ISSUE TITLE
Macro linenum 0-base

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#42]
есть макр для 1-based line num, для красоты хорошо бы еще для 0-based(чтоб было)

CurrentLineNum0
CurrentColumnNum0

**Comment by kvichans** [comment]
Это про шаблоны?

Сейчас ожидаются имена групп в RegExp: `file` `line` `col`.
Если я правильно понял, вы предлагаете еще ожидать группы с именами `line0` и `col0` и делать по ним навигацию со сдвигом на одну строку/колонку. 
Так?

**Comment by Alexey-T** [comment]
нет!! Не про патерны а про макры для подстановки (макро чтобы ставить номер строки от 0)

**Comment by kvichans** [comment]
Ок
