### ISSUE TITLE
button top-y

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#44]
нужна правка- кнопки по краю контролов edit, без -1..-2 пикселя.

**Comment by kvichans** [comment]
не понял: где что поправить?

**Comment by Alexey-T** [comment]
Кнопа делается на 1пкс выше

```
  +[C1.join(['type=edit'      ,POS_FMT(l=PRP2_L,  t=PROP_T[2],  r=PRP2_L+PRP2_W,b=0)
                      ,'val='+ed_ext['file']
                      ])] # i= 3
            +[C1.join(['type=button'    ,POS_FMT(l=PRP3_L,  t=PROP_T[2]-1,r=PRP3_L+PRP3_W,b=0)
                      ,'cap=&Browse...'
                      ])] # i= 4
```

**Comment by kvichans** [comment]
убрать `-1`?
Тогда на Win будет не красиво

**Comment by Alexey-T** [comment]
да, на Вин будет норм..

**Comment by kvichans** [comment]
А можно как-то выяснить на какой платформе работаем?
Кроме ОС (питон скажет) что еще существенно?

**Comment by Alexey-T** [comment]
ничего.

**Comment by Alexey-T** [comment]
лучше бы не делать сложно.

**Comment by kvichans** [comment]
Как я могу сделать вам на Линуксе удобно, а себе  - нет? Рука не поднимается

**Comment by Alexey-T** [comment]
можно сделать

  btn_dy = 1 if <test OS> else 0

**Comment by Alexey-T** [comment]
можно не делать вообще

**Comment by Alexey-T** [comment]
Вообще неважно это

**Comment by kvichans** [comment]
Если не важно, оставлю _как сейчас_
