### ISSUE TITLE
Tidy- regex

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#45]
тул Tidy.exe.
задал `line (?P<line>\d+) column (?P<col>\d+) .+`
При клике- ошибка

```
File is maybe not text:
/home/user/

Do you want to open it?
```

файл /home/user/test.htm

**Comment by Alexey-T** [comment]
Строки

```
line 3 column 24 - Warning: plain text isn't allowed in <head> elements
line 2 column 1 - Info: <head> previously mentioned
```

**Comment by kvichans** [comment]
Не понял: где заноза?

**Comment by kvichans** [comment]
Замените (-2== 2) на (-2==-2) и удалите # в строках 315 319
Что в консоли?

**Comment by Alexey-T** [comment]
Хм,вы можете поставить Tidy и проверить- любой файл htm с кривым тегом, напр. 

```
<h2>ddd</hhh2>
```

**Comment by kvichans** [comment]
попробую

**Comment by kvichans** [comment]
повторил "Cannot find file"

**Comment by kvichans** [comment]
Только сейчас заметил, что в выдаче нет имени файла :)
Буду подставлять текущий, если шаблон не дает файл

**Comment by kvichans** [comment]
выложил

**Comment by Alexey-T** [comment]
bug. `line 1 column 1 ..................`--клик на строку дает прыг в 2:2.

**Comment by kvichans** [comment]
и у меня

**Comment by kvichans** [comment]
пробуйте

**Comment by Alexey-T** [comment]
А вы сделаете группы line, line1, col, col1 (0-based, 1-based)?

**Comment by kvichans** [comment]
Да, это норм
Те, что сейчас: line, col - пусть будут с 1
Добавлю: line0, col0

**Comment by Alexey-T** [comment]
Ок

**Comment by Alexey-T** [comment]
Жду бету..чтобы выложить. Кстати много скачек cudaExt
