### ISSUE TITLE
Commd "Go to next output line"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#47]
> Была идея дать в плагине команду "Перейти на след проблему". Для этого в API вы добавили извлечение строк из output и установку выделенной. Планирую сделать.

**Comment by kvichans** [comment]
В работе...

**Comment by kvichans** [comment]
Почти закончил.
Проблема с tidy. 
- Табуляторы в исходном тексте он воспринимает как сдвиги на 8 колонок.
- В Куд табулятор это один символ при задании ed.set_caret(col, row)
- Перевод из символов в колонки зависит от установок user/lexer/file и вполне может отличаться от "сдвиг на 8"

Есть идеи как это преодолеть?

**Comment by Alexey-T** [comment]
хм.. брать строку файла и вручную считать позицию, tab=8

**Comment by Alexey-T** [comment]
2- ставить tab=8, делать ed.convert, ставить tab=prev_tab

**Comment by kvichans** [comment]
2-й способ попробую. Если дергаться текст не будет, то так и оставлю
