### ISSUE TITLE
Need macros {AppDir} {AppDrive}

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#49]
макрос для портабельности.КИнул тул в подпапку Куды.И надо пускать с флешки.

**Comment by Alexey-T** [comment]
макро надо тестировать в поле "имя файла" и других.

**Comment by kvichans** [comment]
ОК

**Comment by Alexey-T** [comment]
Еще макро {AppDrive}-только для Вин, в Сине это просили 2-3 раза- пример "D:"

**Comment by kvichans** [comment]
ОК

**Comment by kvichans** [comment]
{AppDir} это app_path(app.APP_DIR_EXE) ?
{AppDrive} - ?

**Comment by Alexey-T** [comment]
1-видимо, проверить надо.
2-в пути берете 2 символа, если это os.name=='nt' и s[1]==':'

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
правка к хелп- "aPPlication"

```
CudaText application properties:
   {AppDir}           - Directory with app executable 
   {AppDrive}         - (Win only) Disk of app executable, eg "C:"
```

**Comment by Alexey-T** [comment]
не раб.в поле имени файла. указал {AppDir}/tidy

```
FileNotFoundError: [Errno 2] No such file or directory: '{AppDir}/tidy'
```

**Comment by kvichans** [comment]
Вижу

**Comment by kvichans** [comment]
fix

**Comment by Alexey-T** [comment]
жду бету

**Comment by kvichans** [comment]
выложил

**Comment by Alexey-T** [comment]
не взяли мое описание для окна Хелп. выше.

**Comment by kvichans** [comment]
Да, просто не заметил. Спасибо, перенесу
