### ISSUE TITLE
bt plugin exttools: nav by results

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_exttools#50]
Добавил навигацию на основе результатов тула
- Подменю в Tools с двумя командами "След/Пред результат"
- Реакция на ВВОД/ДвКлик в output

Для работы с tidy появилась расширенная настройка (в Advanced)
source_tab_as_blanks:8

**Comment by Alexey-T** [comment]
отлично.

**Comment by Alexey-T** [comment]
Работает!
