### ISSUE TITLE
ed.focus dont work

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_exttools#51]
Не понимаю, почему фокус не удается передать из output в редактор по ed.focus() в строке 299
Может вы поймете/подскажете?

**Comment by Alexey-T** [comment]
ed.focus() должен раб.-может не выполняется строка

**Comment by kvichans** [comment]
Проверил. 
- Код `ed.focus()` выполняется (последняя строка метода run())
- Фокус остается внутри output

Нужно расследование

**Comment by Alexey-T** [comment]
как повторить в плагине это.

**Comment by kvichans** [comment]
Я запускаю tidy, получаю несколько строк в output и фокус застревает там

**Comment by Alexey-T** [comment]
fixd.Проблема- фокусир-ние панели out было по таймему- уже после выполнения питона

**Comment by kvichans** [comment]
В плагине ничего менять не нужно?

**Comment by Alexey-T** [comment]
нет

**Comment by kvichans** [comment]
Может быть фокус в output вообще не обязательно перемещать?
Сейчас без этого не получится его заполнение. 
`app_log(LOG_SET_PANEL, LOG_PANEL_OUTPUT)` перемещает фокус?
Ведь можно же _показать_, но не _активировать_?

**Comment by Alexey-T** [comment]
фокус от ed.cmd(показать панель)

**Comment by kvichans** [comment]
Вот я и спрашиваю: может есть/будут средства показать без активации?

**Comment by Alexey-T** [comment]
:)А надо? команды?

**Comment by kvichans** [comment]
Сейчас получается _переигрывание_: передаем фокус, забираем фокус.
Конечно, пока можно жить и так.

**Comment by Alexey-T** [comment]
Стоит сделать 3 кмд? 
- панель консоли+ без фокуса, 
- панель out.val+ без фокуса. 

если их делать то клики по табам console/ out/ val будут НЕ делать фокус. плохо?

**Comment by kvichans** [comment]
Три **доп.команды** для показа, но не активации закладок в нижней панели - это хорошо. Мне этого сейчас не хватает.
Я не понял при чем тут клики по ярлыкам нижней панели. Они конечно должны активировать.

**Comment by Alexey-T** [comment]
Хм подумаю как
