### ISSUE TITLE
Idea of ST3

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#52]
Смотрите, идея какая https://packagecontrol.io/packages/Highlight%20Build%20Errors

**Comment by kvichans** [comment]
Да, понятно.
Нужно
- Дать в туле новую опцию "Автоматически раскрашивать строки"
- После запуска тула пройти по его выдаче, найти какие строки упомянуты
- Освоить/использовать API для раскраски фрагментов текста.

Так?

**Comment by Alexey-T** [comment]
да- и использлвать http://wiki.freepascal.org/CudaText_API#bookmark

**Comment by kvichans** [comment]
Потом попробую.

**Comment by Alexey-T** [comment]
неважная фича. Если хотите

**Comment by kvichans** [comment]
Мне еще хотелось не подсветки, а опции "Автоматически переходить на первый результат" - чтобы не нужно было жать NextRes после каждого запуска

**Comment by Alexey-T** [comment]
это нужно!
