### ISSUE TITLE
Output "Bottom hint panel"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#54]
Есть апи msg_status_alt()- для полноты, можно сделать вывод туда?

**Comment by Alexey-T** [comment]
(hint= 1 строка. надо весь вывод делать в 1 стр.)

**Comment by kvichans** [comment]
Не понятно
"У вас"? в плагине?
"можно сделать вывод"? кому сделать?
"диалог [?]"? что за диалог?

**Comment by Alexey-T** [comment]
У вас ext-tools. есть вывод в панель outpt. добавить вывод в новую панель bottom hint panel. опция разрешит выводить вывод тула в hint panel (все в 1 строку)

**Comment by kvichans** [comment]
не понятно
Попробовал msg_status_alt. Вроде бы это доп.статус строка, которая прячется через заданное время. Это и есть bottom hint panel ?

**Comment by Alexey-T** [comment]
да, это оно.

**Comment by kvichans** [comment]
Идея остается непонятной.
Что за "диалог"? Зачем все "в одну строку"?

**Comment by Alexey-T** [comment]
не надо диалог. Надо вывести много строк (если тул дал много строк) в  msg_status_alt

**Comment by kvichans** [comment]
в чем прикол?

**Comment by Alexey-T** [comment]
для полноты.

**Comment by kvichans** [comment]
(потерял надежду понять)

**Comment by Alexey-T** [comment]
есть Апи для вывода строки. Для полноты хочется чтобы плагин мог выводить в это апи

**Comment by kvichans** [comment]
Все остальные способы **хранят** все выданных тулом строки
А msg_status_alt показывает только одну, да и эту теряет через некоторое время
Зачем это?

**Comment by Alexey-T** [comment]
Верно. Зачем, в Hippoedit видел
