### ISSUE TITLE
Macro for Initial folder

### ISSUE THREAD

**Issue by myCrack** [kvichans/cuda_exttools#59]
Если для рабочего каталога указать макрос, например `{FileDir}`, то при запуске внешнего инструмента, все правильно работает, а при переходе к файлу из Output Window, подстовляется `{FileDir}\Тут_будет_название_файла`, т.е. макрос не разварачивается.

**Comment by kvichans** [comment]
Да, хорошая дыра. Сходу не закроешь

**Comment by kvichans** [comment]
Потестируйте
Потом сборку/релиз сделаю

**Comment by myCrack** [comment]
Вроде как работает, но заметил что еще макрос не разворачивается, когда вызываем внешний инструмент, то в строке состояния пишется `Call: _пудь_до_компилятора_ {FileNameNoExt}`

**Comment by kvichans** [comment]
Это специально так показывается
