### ISSUE TITLE
Err, linux

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#6]
сделал тул (файл /usr/bin/tidy -тут нет расширения)
парам {FileName}. захват. запуск-

```

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_exttools/__init__.py", line 265, in run
    subprocess.Popen(cmd)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/tidy /home/user/test.htm'
```

**Comment by kvichans** [comment]
А как выглядит запуск в ком.строке линукса?

**Comment by Alexey-T** [comment]
"/usr/bin/tidy /dir/nn.htm"

**Comment by kvichans** [comment]
Не понятно. Надеюсь изучение плагина Субл прояснит.

**Comment by Alexey-T** [comment]
Лог говорит что не найден файл- имя файла- еще и параметр в имени.

**Comment by kvichans** [comment]
Есть предположение, что только на Win  subprocess.Popen можно подавать одной строкой и файл и параметры запуска, а для Unx нужно оформлять раздельно
subprocess.Popen([cmnd, prms], ...)
Выложил обновление.

**Comment by Alexey-T** [comment]
Поправилось
