### ISSUE TITLE
Wrong caret position when error jamp

### ISSUE THREAD

**Issue by myCrack** [kvichans/cuda_exttools#60]
Когда после запуска внешнего инструмента, если перехватывать его вывод, то потом щелчком мыши по строке в Output Window, редактор пеерходит к этой строке, так вот, если в регулярном выражении не указывать номер колонки, например при таком шаблоне `^(?P<file>.+?)\((?P<line>\d+)\):\s` то каретка встает на нужную страку, но калонка будет та, что была до запуска внешнего инструмента, а надо чтобы в начало строки.

**Comment by kvichans** [comment]
Да, согласен.
Todo

**Comment by kvichans** [comment]
fix
