### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#61]
файл нужен в папке readme- issues.txt

```
Report issues at plugin page:
https://github.com/kvichans/cuda_exttools/issues
```

**Comment by kvichans** [comment]
Поясните. Это нужно для всех плагинов?

**Comment by kvichans** [comment]
Как это будет использовать Куд?

**Comment by Alexey-T** [comment]
лучше для всех. никак.

**Comment by kvichans** [comment]
Тогда зачем это?

**Comment by Alexey-T** [comment]
Чтобы myCrack нашел как репортить

**Comment by kvichans** [comment]
не понял
добавлю

**Comment by Alexey-T** [comment]
чтобы другие нашли issues.

**Comment by kvichans** [comment]
как они узнают, что нужно заглядывать в этот файл?

**Comment by Alexey-T** [comment]
он в папке readme.

**Comment by Alexey-T** [comment]
Давайте класть строку с урл в файл install.inf, поле homepage= ? не делать файлов в readme
Addonman может потом юзать это

**Comment by kvichans** [comment]
Хорошо.
Дополню в своих *.inf раздел [info] строками вида
homepage=https://github.com/kvichans/cuda_exttools
