### ISSUE TITLE
with localized ui

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#62]
-берем бету
-в переводе (data/lang/*.ini) меняем имя меню plugins.
-юзаем перевод- options/transl.
-плагин падает. ищет "&Plugins"

**Comment by Alexey-T** [comment]
Дал возм-ть решить это
Есть хинты для меню top

```
>>> =app_proc(PROC_MENU_ENUM, 'top')
&File|file
&Edit|edit
Select&ion|sel
&Search|search
&View|view
&Plugins|plugins
&Options|opt
&Help|help

```

**Comment by Alexey-T** [comment]
пач

```
#       if 0==self.id_menu:
            # Create AFTER Plugins
            top_nms = app.app_proc(app.PROC_MENU_ENUM, 'top').splitlines()
            pass;              #LOG and log('top_nms={}',top_nms)

            plg_ind = -1
            for i in range(len(top_nms)):
                s1, s2 = top_nms[i].split('|')
                if s2=='plugins':
                    plg_ind=i+1
                    break

            id_menu = app.app_proc( app.PROC_MENU_ADD, '{};{};{};{}'.format('top', 0, '&Tools', plg_ind))
            ed.exttools_id_menu = id_menu               ##?? dirty hack!
```

**Comment by kvichans** [comment]
Этот хак (вставка после п. Plugins) появился из-за того, что API не дает при перечислении id-ы подветок. Может уже пора доработать API?

**Comment by kvichans** [comment]
Будет ли теперь `=app_proc(PROC_MENU_ENUM, )` возвращать id-ы всех веток?

**Comment by Alexey-T** [comment]
выше написал же.

**Comment by kvichans** [comment]
Осталось не понятно: это только для top?

**Comment by Alexey-T** [comment]
да, а нужно еще?

**Comment by kvichans** [comment]
Да, нужно возвращать ранее присвоенные id для всех веток

**Comment by kvichans** [comment]
Про патч.
Хочу сделать, чтобы работало во всех версиях Куд.
С какой версии `app_proc(PROC_MENU_ENUM, 'top')` возвращает не `&Plugins`, а `&Plugins|plugins`?
Сейчас версия `1.2.28.0`. А на предыдущей как работало?

**Comment by kvichans** [comment]
Внес исправление в репозиторий.
Сделал поиск индекса как вы предложили, но одной строкой

```
plg_ind = [i for (i,nm) in enumerate(top_nms) if '|plugins' in nm][0]
```

Скоро выпущу большое обновление плагина - тогда сделаю сборку.

**Comment by Alexey-T** [comment]
с версии Апи 131.

**Comment by kvichans** [comment]
Переделаю на проверку версии АПИ

**Comment by Alexey-T** [comment]
> код

да, list comprehent лучше...
