### ISSUE TITLE
Пользовательские макроподстановки

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#64]
Paths to libs and includes folders assigned to variables, which can be inserted into command line information  - SynWrite has a section under project settings that i think would accomplish this 

so $LIB=M:\Masm32\Lib, $INCLUDE=M:\Masm32\Include 

This is what RadASMs paths and project options dialogs look like 

![radasmpathsdialog](https://cloud.githubusercontent.com/assets/4154978/13727618/3f89e404-e90a-11e5-90ae-75280a19869e.png)
![radasmprojectoptions](https://cloud.githubusercontent.com/assets/4154978/13727619/3f8c3c36-e90a-11e5-880f-00702d8b1fa6.png)

**Comment by Alexey-T** [comment]
- переменные задаются или для 1 тула или всех? не знаю.
- есть шаблоны(radAsm)- можно из шаблона видимо создать Н тулов (1- make, 2- build, 3-link.....)

**Comment by kvichans** [comment]
Можете сжато пояснить, о чем речь?

**Comment by Alexey-T** [comment]
определять переменные. Определил $dir, $exe, могу во всех тулах прописать поля с переменными $dir $exe. Может надо делать группы переменных- если включили в туле группуА, то переменые юзаются из групыА

**Comment by Alexey-T** [comment]
(memo с INI файлом- тогда секция=группа, ключ=переменная. В туле выбирать группу)

**Comment by kvichans** [comment]
Подумаю, как это добавить

**Comment by Alexey-T** [comment]
один раз определил переменные.  в 3-4 тулах вызываешь их. задал новые пути в переменых-- тулы стали другие.

**Comment by kvichans** [comment]
Идея стала понятна - дополнить список из готовых макросов ({AppDir},...) ручными макросами. Хорошее дело.

**Comment by kvichans** [comment]
Первая реализация.
Попробуйте/покритикуйте

**Comment by Alexey-T** [comment]
написал- мейл.
