### ISSUE TITLE
i18n dont work

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#65]
ничего нет по-русски, даже после рестарта Куд. Линукс Ubuntu 14.4

**Comment by Alexey-T** [comment]
```

THIS_DIR= app.app_path(app.APP_DIR_EXE)+'/py/{0}/'.format(THIS)
```

потому что в Лин папка Ехе совсем НЕ рядом с 'py'

**Comment by kvichans** [comment]
а-а-а
Как правильно?

**Comment by kvichans** [comment]
Как доступиться к папке, где лежит плагин?

**Comment by Alexey-T** [comment]
```
THIS_DIR= app.app_path(app.APP_DIR_PY)+'/{0}/'.format(THIS)
```

**Comment by Alexey-T** [comment]
Не перевели "shell command"

**Comment by kvichans** [comment]
Про APP_DIR_PY не знал. Поправлю.
Может есть надежный (для разных ОС) способ узнать _свою_ папку? Мне нужно залезать в подпапку от текущего модуля?

**Comment by Alexey-T** [comment]
`__file__`

**Comment by Alexey-T** [comment]
```
config_dir = os.path.join(os.path.dirname(__file__), 'configs')
```

**Comment by kvichans** [comment]
да - это самое лучшее
