### ISSUE TITLE
i18n detect 'ru'

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#66]
Сделать детект для всех языков-
https://sourceforge.net/projects/cudatext/files/addons/translations/

**Comment by kvichans** [comment]
Поясните

**Comment by Alexey-T** [comment]
получать langID через словарик. Не как вы. вы берете str[:2]. для Китай-Португалия плохо это

**Comment by kvichans** [comment]
Не понятно
Словарь поможет перевести то, что возвращает `app_proc(PROC_GET_LANG, '')` в landID?

**Comment by Alexey-T** [comment]
'' -> 'en'
'Russian'->'ru'
'Portugese sdfsdf'->'pt_PT'
'Portugese Brazil'->'pt_BR'

**Comment by kvichans** [comment]
Осталось не понятно как этот словарь применять

**Comment by Alexey-T** [comment]
вы получили строку 'Russian'. из апи. по этой строке по словарику получили langID. 'ru'. или я сделаю в имени файла lang id- `russian (ru_RU).ini`
