### ISSUE TITLE
Rust-style

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#67]
https://github.com/kylepink/RustCodeFormatter Возможно (можно ли? хватит ли тула?) сделать все это- без плагина?
Тулом? скачать руст-стайл. и тп

**Comment by kvichans** [comment]
Поясните идею/вопрос.
1. Если это внешняя утилита, которая меняет текст текущего файла, то что будет препятствовать вызову ее через Тул? Есть какая-то особенность?
2. Может быть вы про то, чтобы добавлять Тулы не руками, а каким-то инсталятором? Например, пользователь скачивает zip, открывает его в Куд, подтверждает, что-то устанавливается - и появляется новый, готовый к использованию Тул. Так? Тогда нужно договориться про API от плагина, которое позволит делать действия вместо GUI. Это мне нравится

**Comment by Alexey-T** [comment]
мне интересно, ExtTools сможет сделать то что делает плагин RustCodeFormatter?
Если вам лень смотреть (что делает RustCodeFmt) -забейте

**Comment by kvichans** [comment]
Забил

**Comment by Alexey-T** [comment]
Okey
