### ISSUE TITLE
показ Макро, evaluate

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#70]
зачем тут 2 раза путь?

![ff1](https://cloud.githubusercontent.com/assets/4154978/14399564/d2c4cd98-fdfe-11e5-9919-3f24cfad8570.png)

**Comment by kvichans** [comment]
Это вы задали простую строку. Если бы в значение вставили другой макро, то в первой строке показывалось "что ввели", а во второй - "после всех подстановок"
