### ISSUE TITLE
Join tool: cannot move down

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#71]
- создал join tool, в списке 2 тула
- св-ва этого тула
- тул 1-й (список series) не опускается по кнопке Down

![too2](https://cloud.githubusercontent.com/assets/4154978/14399786/42667dde-fe01-11e5-8798-fd804f7e1d9d.png)

**Comment by Alexey-T** [comment]
написал понятнее.

**Comment by kvichans** [comment]
Воспроизвел. ToDo
