### ISSUE TITLE
Listview is bad

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#74]
Тут видно,
- названия колонок потерлись, что такое Captur, Savi, не понятно
- что такое Capture:OP, N, непонятно
- Params не видно дальше длины {filename}

==> нужен _простой_ список

![tool](https://cloud.githubusercontent.com/assets/4154978/17078473/161a97cc-5105-11e6-993e-9ad12e73a4d8.png)

**Comment by kvichans** [comment]
- Названия колонок не "потерлись", а "обрезались". 
- Значения в колонке `Capture` сейчас действительно _загадочные_. Знаете как улучшить?

Пробовали нажимать `Adjust`, чтобы увеличить ширины колонок?

**Comment by Alexey-T** [comment]
Это плохая идея - ширины колонок, нужно 1 или 3 колонки- имя, файл, параметры (если одинак. файл)

**Comment by kvichans** [comment]
Можете **скрывать** колонки в Adjust. Там в титуле диалога есть упоминание, что "-" перед шириной означает "скрыть".

**Comment by Alexey-T** [comment]
раньше не видел!

![fff](https://cloud.githubusercontent.com/assets/4154978/17078697/d251462a-510a-11e6-815c-3daaee9be2da.png)

**Comment by kvichans** [comment]
:) Это достаточное решение?

**Comment by Alexey-T** [comment]
надо поменьше caption, чтобы про "-" видно.

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
Column prefix "C"/"R" to align, "-" to hide

**Comment by kvichans** [comment]
ok
