### ISSUE TITLE
confirm del

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#75]
- иконку лучше questn - или warn
- !!!!!!!!!!!!! не смотрится, лучше "--- WARNING ---"

![warr](https://cloud.githubusercontent.com/assets/4154978/17078731/bc84cce4-510b-11e6-88ab-0fdb7102f327.png)

**Comment by kvichans** [comment]
Да - info здесь плохо
Не понял как тут можно использовать warn, а не question
Будет question
