### ISSUE TITLE
Need to sort var list

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#77]
Else it is ugly like

ProjDir
v2
ProjMainfile
v1
AppDir

![proj_](https://cloud.githubusercontent.com/assets/4154978/18307062/bb71ff4e-74ff-11e6-8aa3-19cc7cab04c8.png)

**Comment by kvichans** [comment]
Какая сортировка была бы полезна?
Сейчас выдаются 
- сначала все переменные заданные в **пользователем** Tools
- потом все переменные из Проекта (в том порядке, как они извлекаются из переданного dict)
- в конце все **встроенные** переменные Tools

**Comment by Alexey-T** [comment]
Этап2 (извлечение из dict)- сортировать- ProjDir ProjMainFile others

**Comment by kvichans** [comment]
не понял - как это?

**Comment by Alexey-T** [comment]
если я сделаю OrderedDict для proj_var(), то вы его покажете?

**Comment by kvichans** [comment]
как это сделать, если плагин **не знает**, какие там ключи?

**Comment by kvichans** [comment]
Да - OrderedDict хорошее решение

**Comment by Alexey-T** [comment]
я могу сделать сортировку.
Если сделаю не dict, а OrderedDict.

**Comment by kvichans** [comment]
мой плаг для этого уже готов

**Comment by Alexey-T** [comment]
Upd PrMan
