### ISSUE TITLE
Tidy error

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#8]
все время получается вывод (Output pane)

```
line 1 column 1 - Warning: inserting missing 'title' element
Info: Document content looks like HTML 3.2
1 warning, 0 errors were found!

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">
<html>
<head>
<meta name="generator" content=
"HTML Tidy for Linux (vers 25 March 2009), see www.w3.org">
<title></title>
</head>
<body>
</body>
</html>

To learn more about...
```

Запуск в консоли- 

```
tidy -errors -quiet "/home/user/test.html"
```

дает норм вывод

```
line 1 column 1 - Warning: specified input encoding (iso-8859-1) does not match actual input encoding (utf-8)
line 1 column 5 - Warning: missing <!DOCTYPE> declaration
line 3 column 24 - Warning: plain text isn't allowed in <head> elements
line 2 column 1 - Info: <head> previously mentioned
line 3 column 24 - Warning: inserting implicit <body>
line 4 column 1 - Warning: </head> isn't allowed in <body> elements
line 3 column 24 - Info: <body> previously mentioned
line 5 column 17 - Warning: discarding unexpected <body>
line 16 column 1 - Warning: missing </div>
```

запуск ИзКуд дает такой лог

```
Command.run:227 nm, raw-cmd=Tidy tidy -errors -quiet "{FileName}"
Command.run:254 ready   prms=-errors -quiet "/home/user/test-tree.html"
Command.run:269 ?? Popen
Command.run:279 ok Popen
Command.run:297 out_ln=line 1 column 1 - Warning: inserting missing 'title' element
Command.run:297 out_ln=Info: Document content looks like HTML 3.2
Command.run:297 out_ln=1 warning, 0 errors were found!
Command.run:297 out_ln=
Command.run:297 out_ln=<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">
Command.run:297 out_ln=<html>
Command.run:297 out_ln=<head>
Command.run:297 out_ln=<meta name="generator" content=
Command.run:297 out_ln="HTML Tidy for Linux (vers 25 March 2009), see www.w3.org">
Command.run:297 out_ln=<title></title>
Command.run:297 out_ln=</head>
Command.run:297 out_ln=<body>
Command.run:297 out_ln=</body>
Command.run:297 out_ln=</html>
Command.run:297 out_ln=
Command.run:297 out_ln=To learn more about 
```

Тул-

![tidy](https://cloud.githubusercontent.com/assets/4154978/11777448/ae352342-a25f-11e5-8f4f-4be710780569.png)

**Comment by Alexey-T** [comment]
Игнорирует файл вообще.
файл-

[test-html.zip](https://github.com/kvichans/cuda_exttools/files/61006/test-html.zip)

**Comment by kvichans** [comment]
это мой брак - забыл отключить лог
замените "(-2==-2)" на "(-2== 2)"

**Comment by Alexey-T** [comment]
я НЕ про лог. Я про вывод tidy--он игнорит файл.

**Comment by kvichans** [comment]
А почему короткое имя tidy будет нормально вызываться из Куд?
Попробуйте вписать в поле File полный путь

**Comment by kvichans** [comment]
Видимо вы в консоли, как-то по-другому формируете окружение - и поиск "что запускать" получается успешным

**Comment by Alexey-T** [comment]
полный путь--то же (сначала был полный-потом уже "tidy")

**Comment by Alexey-T** [comment]
решение- 

```
        pipe    = subprocess.Popen([cmnd]+shlex.split(prms)
                                , stdout=subprocess.PIPE
                                , stderr=subprocess.STDOUT
                               #, universal_newlines = True
                                , shell=False)
```

из-за кавычек было плохо---и еще НАДО ВСЕГДА сплитить аргс в массив

**Comment by kvichans** [comment]
пробую...

**Comment by kvichans** [comment]
Что происходит по командам
- ed.cmd(cmd_FileNew)
- ed.set_text_line(-1, out_ln)
  ? 

У меня вчера нормально работало. А сегодня:
- создается новая вкладка
- строки дописываются к тому тексту, который был активным до создания новой

Как надежно перейти к заполнению новой вкладки?

**Comment by Alexey-T** [comment]
file_open('');ed.set_text_all('aaaaaaaaa')

**Comment by kvichans** [comment]
пробую..

**Comment by kvichans** [comment]
Выложил обновление. Жду тестов

**Comment by Alexey-T** [comment]
плохо- кавички портят опять

```
Command.run:227 nm="Tidy", cmnd="tidy", raw-prms="-errors -quiet "{FileName}""
Command.run:253 ready prms=-errors -quiet "'/home/user/test.html'"
Command.run:266 val4call=['tidy', '-errors', '-quiet', "'/home/user/test.html'"]
```

у меня было ок

**Comment by kvichans** [comment]
Вот же ж засада - тришкин кафтан!
Если не ставить repr(...), то в Win путь файла теряет \
Если ставить, то "лишние кавычки"
Думаю...

**Comment by Alexey-T** [comment]
'r"' + str + '"'

**Comment by kvichans** [comment]
да, возможно
но только не для строк содержащих "

**Comment by Alexey-T** [comment]
shlex.split() сначала уберет "

**Comment by kvichans** [comment]
пробую..

**Comment by kvichans** [comment]
Не сходится
Пытаюсь вызвать Син с тек.файлом
file: c:\Programs\SynWrite\Syn.exe'
params: {FileName}

Вашим способом получаю в prms значение 
r"c:\Programs\CudaText\py\cuda_exttools__init__.py"
После
val4call  = [cmnd]+shlex.split(prms)
вижу в val4call значение
['c:\Programs\SynWrite\Syn.exe', 'rc:\Programs\CudaText\py\cuda_exttools\**init**.py']

И ясно, что файл 'rc:\Programs\...' не найден

**Comment by Alexey-T** [comment]
Сделать сначала split, потом замену в массиве {FN}

**Comment by kvichans** [comment]
пробую..

**Comment by Alexey-T** [comment]
(или можно как счас но не приделывать 'r')

**Comment by kvichans** [comment]
На Win работает
Пробуйте в Lnx

**Comment by Alexey-T** [comment]
quot(). вы ставите кавыч. сами. Нехорошо- в Сине он должен делать кавыч для всех {file}- тут не так

**Comment by Alexey-T** [comment]
Если я хочу приписать к filename строку- ваш код не даст- "{FileName}.bak" в син

**Comment by kvichans** [comment]
Не понял чего "он должен делать в Сине" и чего "код не даст"

**Comment by Alexey-T** [comment]
не даст передать такую строку парам-ов

-bak "{FileName}.bak"

**Comment by kvichans** [comment]
Я начинаю подозревать, что у этой головоломки не решения

**Comment by Alexey-T** [comment]
если так?
- разбить парам-ры по split
- в каждом эл массива делать замены {nnnnnnn}

тогда будет как в Син- и можно передать -bak "{Filename}.bak"

**Comment by kvichans** [comment]
"как в Син"?

**Comment by Alexey-T** [comment]
да- там надо писать кавычки в диалог

**Comment by kvichans** [comment]
Кавычки в любом случае нужно писать, так как в значении {Filename} могут быть пробелы

**Comment by Alexey-T** [comment]
Тогда зачем делаете quot. ?

**Comment by kvichans** [comment]
По вашему совету: 'r"' + str + '"'
У меня в голове уже каша. 
Быстрого решения не нашли. Буду медленно искать решение головоломки

**Comment by Alexey-T** [comment]
Совет с r"..." отменяю- просто замените {Filename} (quot не нужен. сначала конечно делать split)

**Comment by Alexey-T** [comment]
Плс, не делайте quot- и потестируйте с параметрами c кавычк.

**Comment by Alexey-T** [comment]
Плс, не делайте quot- и потестируйте с параметрами c кавычк. и пробелами

**Comment by kvichans** [comment]
Мне не понятно на каком уровне происходит сбой
В Popen я подаю
`['c:\\Programs\\SynWrite\\Syn.exe', "'c:\\Programs\\CudaText\\py\\cuda_exttools\\__init__.py'"]`
От Син получаю сообщение, что он `Не нашел __init__.py' Создать?` (одиночная кавычка за .py - так в сообщении)
- Может быть Син не умеет принимать закавыченный параметр?
- Может Popen что-то портит?

Попробуйте новую версию. 
- Подстановки в каждом слове
- shlex.quote для _умного_ закавычивания

Может подскажете, что с Син не сходится

**Comment by Alexey-T** [comment]
Син ОК- это вы передаете лишние кав-ки в параметре- там и ' и "
уберите все кавычки в пар-рах

**Comment by kvichans** [comment]
А как Син принимает имена файлов, если они с пробелами?

**Comment by Alexey-T** [comment]
Popen сам даст кавычки Винде

**Comment by kvichans** [comment]
проверяю..

**Comment by kvichans** [comment]
А вызов Син с передачей `-bak "{FileName}.bak"` - это корректно для Син? Он такое понимает?

**Comment by Alexey-T** [comment]
split разоб-ет это на 2 пар-ра. Потом popen даст кавычки
Син поймет

**Comment by kvichans** [comment]
Заменил
`prms_l[ind] = shlex.quote(prm)`
на 
`prms_l[ind] = prm`
В Win все проходит (кроме syn с `-bak "{FileName}.bak"`). Попробуйте сами заменить и потестировать в Lnx

**Comment by Alexey-T** [comment]
см..

**Comment by Alexey-T** [comment]
- надо как сделали
- и еще shell=False !

все.

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
Плс, другие isue

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
Update нужен

**Comment by kvichans** [comment]
Поясните пожелание про "shell=False"
Если shell=True, то запускаются и файлы и команды шела (DOS для Win)
Если shell=False, то только файлы
Разве это правильно?

**Comment by Alexey-T** [comment]
Shell=True не запускает tidy (и с путем)

**Comment by kvichans** [comment]
Ясно, значит нужно добавлять свойство
Делаю..

**Comment by Alexey-T** [comment]
да!
