### ISSUE TITLE
Tool type "URL"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#81]
RJTextEd adds tool type (for its tools) 

```
Added a new tool item type "URL". It can be used to open an online search page like "https://www.w3.org/2009/cheatsheet/#search".
Ex.
    Sub menu: Online Search
    Menu text: W3 CheatSheet
    Type: URL
    Command: https://www.w3.org/2009/cheatsheet/#search,
    Argument: [CurrentWord]
```

Can u add it too?

**Comment by kvichans** [comment]
Уточните: что изменить?

**Comment by Alexey-T** [comment]
сделать кнопку Add с выбором - тул обычный или тул линк.
или сделать кнопку Add link - добавить тул-линк.
в свойствах тул-линка, не показывать многие поля.

**Comment by kvichans** [comment]
Я не понял, что значит тул-линк.

**Comment by kvichans** [comment]
Можно ли тул-линк реализовать через тул?

**Comment by Alexey-T** [comment]
Это тул- у него  св-во URL
e.g. http://www.com/www{CurrentWord}

**Comment by Alexey-T** [comment]
нет, его надо пускать через webbrowser.

**Comment by kvichans** [comment]
Что значит "через браузер"? чем это отличается от вызова exe?
Может это вызов "через ассоциацию"?

**Comment by Alexey-T** [comment]
Значит что через import webbrowser; webbrowser.open\* (методы чтобы открыть браузер)

**Comment by kvichans** [comment]
В Win-API есть вызов "через ассоциацию": ShellExecute из shell32.dll (подозреваю что и Лин/Мак есть что-то подобное). Это способ запускать приложения зная только его документы: 
- для *.txt вызывается Куд/Син/...
- для *.doc вызывается Word/Writer/...
- для *.html вызывается браузер
- для http://\* вызывается браузер

Было бы лучше задействовать этот механизм, а не встраивать в плаг вызов **только** браузера.
Проблема в том, что я не знаю как этот механизм зацепить из питона.

**Comment by Alexey-T** [comment]
> Было бы лучше задействовать этот механизм

наоборот - надо исп-ть модуль. Там очень просто-

```
>>> import webbrowser as w
>>> w.open_new_tab('http://ya.ru')
```

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
1. Добавил URL-ы в отдельную вкладку и для них свой диалог Свойств.
2. Разрешил вызывать их прямо из диалога Настройки
3. Оказалось, что через `import webbrowser as w; w.open_new_tab(ref)` можно вызывать и локальные файлы (по протоколу `file:///path` будет запускаться ассоциированное приложение) и много еще чего (по `mailto:adress` можно создать письмо)

**Comment by Alexey-T** [comment]
Спасибо- потестю
