### ISSUE TITLE
URLs dialog size

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#85]
wish: Make dlg size == equal to tools dlg size. Place same btns as SAME positions (up, down, adjust, macros)

**Comment by kvichans** [comment]
Не понятно

**Comment by Alexey-T** [comment]
2 таба (тулы, url) делают 2 диалога, они разных размеров.
Виш- делать 1 размер.
Виш- делать кнопки на одном месте (up, down, adjust)

**Comment by kvichans** [comment]
Не понятно - уже так и должно работать

**Comment by Alexey-T** [comment]
только что поправили.

**Comment by Alexey-T** [comment]
Ubuntu двигает длг- думал он меняется

**Comment by kvichans** [comment]
Хорошо бы не бросать этот взбрык и разобраться что происходит и поймать причину

**Comment by Alexey-T** [comment]
Ubuuntu показыв. длг то левее,то правее, думал меняет размер
