### ISSUE TITLE
Url hotkey cannot set

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#86]
при создании URL нельзя задать хоткей (Длг хоткея не вызыв.), но потом если открыть этот тул в длг -то можно...

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
Дал аннонс- можно выложить

**Comment by kvichans** [comment]
И для тула и для урла нельзя назначить хоткей пока он не сохранен.
Перенес назначение хоткеев в основной диалог, а в диалогах свойств остались только информационные поля

**Comment by kvichans** [comment]
Опубликовал
