### ISSUE TITLE
Wrong result if find-string has quote

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#88]
здесь 100 рез-тов и все неверные.

**Comment by kvichans** [comment]
Мне сложно понять: нажата ли кнопка ".*"?

**Comment by kvichans** [comment]
Если "нажата", то почему результаты "неверные"? Найдены одиночные символы из указанного перечисления

**Comment by Alexey-T** [comment]
Ааа.Нажата ведь
