### ISSUE TITLE
todo for me. DashDoc

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#89]
Want to do experiment. Modelize this on ExtTools on MAC
https://packagecontrol.io/packages/DashDoc
todo for me

**Comment by kvichans** [comment]
Интересно попробовать интеграцию с [Zeal](https://zealdocs.org/)

**Comment by Alexey-T** [comment]
Попробуйте, работает? не знал про Зил.

**Comment by kvichans** [comment]
Что попробовать?

**Comment by Alexey-T** [comment]
Zeal под Win32
Деш работает!! вот тут пригодился УРЛ. Делаем тул с урл
Вот отсюда все ясно

```

        if platform.system() == 'Windows':
            # sending keys=<nothing> confuses some Windows doc viewers
            if keys:
                # ampersand must be escaped and ^ is the Windows shell escape char
                url = 'dash-plugin://keys=%s^&query=%s' % (','.join(keys), quote(query))
            else:
                url = 'dash-plugin://query=%s' % quote(query)
            subprocess.call(['start', url], shell=True)
        else:
            subprocess.call(['/usr/bin/open', '-g',
'dash-plugin://keys=%s&query=%s' % (','.join(keys), quote(query))])
```

**Comment by Alexey-T** [comment]
Нужно макро для Деша, {CurrentWord}

**Comment by Alexey-T** [comment]
Как сделать готовый тул для Деша и распр-ть? Юзеру трудно набить "dash-plugin://keys=..."
Как сделать exttool.nnnnnnnnn.zip для Куд.
Субл может распр. тулы

**Comment by kvichans** [comment]
Да, нужно добавить в интерфейс плага методы, чтобы Куд мог ему передавать готовые тулы.
Куд будет их брать в Сети.

**Comment by kvichans** [comment]
1. Нужен ли новый формат для "раздаваемого"? 
   Сейчас уже есть подгрузка линтеров для плага Lint. Можно ли приспособить формат этих дополнений для подгрузки данных к другому плагу?
2. Куд уже передает линту эти дополнения. Можно использовать этот способ для Тул-плага?

**Comment by Alexey-T** [comment]
можно продолжить в новой теме.

**Comment by kvichans** [comment]
ОК - продолжим про раздаваемые тулы отдельно
Здесь продолжим тему про DashDoc

---

Вы написали

> Zeal под Win32
> Деш работает!! вот тут пригодился УРЛ. Делаем тул с урл
> Вот отсюда все ясно

Мне не ясно. Поясните, что установить, как запустить

**Comment by Alexey-T** [comment]
знаю только про Dash for Mac. Zeal видимо под Win?

**Comment by kvichans** [comment]
Да

**Comment by Alexey-T** [comment]
Деш открывает УРЛ вида - см код выше- как firefox

**Comment by kvichans** [comment]
Что такое DashDoc ? Это чисто Маковая штука?

**Comment by Alexey-T** [comment]
это плагин для Субл, для Dash

**Comment by kvichans** [comment]
Фраза "для Деша" имеет смысл только под Мак?

**Comment by Alexey-T** [comment]
да, а Зил делает то же

**Comment by kvichans** [comment]
Установил Zeal. 
Создал урл-тул: `dash-plugin://keys=python:{CurrentWord}`.
Выделил в коде `replace`.
При вызове тула активизируется Zeal.
Но в Zeal в строке поиска отображается `python:replace:` - и конечно последний `:` мешает.
Не могу сообразить, на каком этапе добавляется лишний `:`.
При запуске из плагина `webbrowser.open_new_tab(ref)` в `ref` этого символа нет.

**Comment by kvichans** [comment]
Сообразил! Правильная ссылка: `dash-plugin://query=python:{CurrentWord}`.
Заработало :)

**Comment by Alexey-T** [comment]
надо задать keys=python, query=<....>

**Comment by kvichans** [comment]
Не смог понять деталей оформления ссылки в примере из ваше поста
`url = 'dash-plugin://keys=%s^&query=%s' % (','.join(keys), quote(query))`
И еще там используется вызов через 
`subprocess.call(['start', url], shell=True)`
В тул-урлах это не будет работать.

Как нужно оформлять для вызова через `webbrowser.open_new_tab(ref)` можете подсказать?

**Comment by Alexey-T** [comment]
так и нужно. Делать урл, где  keys=Python, query=запрос
`'dash-plugin://keys=%s^&query=%s' % (','.join(keys), quote(query))`

знак ^ тут для cmd.exe шела- не надо

**Comment by kvichans** [comment]
Вот я и путаюсь с синтаксисом.
Вот так видимо будет работать:
`'dash-plugin://keys={}&query={}'.format(','.join(keys), quote(query))`
Только не понятно что делает `quote()`

**Comment by Alexey-T** [comment]
про quote наверное есть хелп. в urllib.

**Comment by kvichans** [comment]
Их таких много. Видимо это `shlex.quote`

**Comment by Alexey-T** [comment]
https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote

**Comment by kvichans** [comment]
спасибо

**Comment by Alexey-T** [comment]
quote надо делать Урл-тулам.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Мутное это дело. Поставил
`webbrowser.open_new_tab(urllib.parse.quote(ref, safe='/:'))`
Проверил, что работает на ссылках
`dash-plugin://`
`mailto:`

Но для этой ветки 
`https://github.com/kvichans/cuda_exttools/issues/89#issuecomment-253261452`
получилось неправильная ссылка
`https://github.com/kvichans/cuda_exttools/issues/89%23issuecomment-253261452`

**Comment by kvichans** [comment]
Добавил `#` к
`webbrowser.open_new_tab(urllib.parse.quote(ref, safe='/:#'))`
Эта ветка стала открываться. Но это "подбор" без понимания ситуации.

**Comment by Alexey-T** [comment]
Вы подобрали `:/#` и можно `?&` и окей, наверно не надо еще символов

**Comment by Alexey-T** [comment]
Надо quote не весь урл а только параметры в конце. которые curword в Деш.
