### ISSUE TITLE
Unkillable last line end

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_exttools#9]
Невозможно избавиться от последнего перехода на новую строку.
Если это только визуальных эффект, то он запутывает: невозможно отличить когда файл заканчивается на \n, а когда нет.

**Comment by Alexey-T** [comment]
Можете не плюсовать строку.А делать set_text_line(get_line_count()-1, ...)

**Comment by kvichans** [comment]
Ошибся репозиторием. Продублировал в CudaText
