### ISSUE TITLE
wish. Macro {CurrentWord}

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#91]
word at 1st caret. Considers word-chars (Cud option)

**Comment by kvichans** [comment]
Good
ToDo

**Comment by kvichans** [comment]
Если первая каретка не "голая", а задает выделение, то что считать "текущим словом"?
Обычно это выделение и используется. Так?
Или игнорировать выделение?

**Comment by kvichans** [comment]
Требуется обкатка

**Comment by Alexey-T** [comment]
Так- брать выделение

**Comment by Alexey-T** [comment]
get_current_word(ed, cCrt, rCrt)
зачем тут каретку передавать. Одного ed хватит.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
Жду тестового применения

**Comment by Alexey-T** [comment]
Да-работает, с eng+rus
