### ISSUE TITLE
wish: tool CertTools

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#92]
plugin is only a tool running:
https://github.com/Gui13/sublime-certtools
can we have tool as zip?

**Comment by Alexey-T** [comment]
```
        cert_result = subprocess.check_output(["openssl", "x509", "-text", "-noout", "-in", filename]).decode('utf-8')
..
    new_buffer = sublime.active_window().new_file()
    new_buffer.insert(edit, 0, cert_result)
```

**Comment by kvichans** [comment]
Про что wish?

**Comment by Alexey-T** [comment]
сделать тул который бы вызывал эту программу- certtools. использовать механизм тулов в внешних файлах. в zip...

**Comment by kvichans** [comment]
Опять не понял. Чем отличается от обычного тула?

**Comment by Alexey-T** [comment]
это должен быть zip file с тулом.
