### ISSUE TITLE
wish: macro {q}

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#94]
macro {q} before {some} means: 
value of {some} must be encoded 
- urllib.quote()

e.g. word is пппп:
{q}{CurrentWord} 
is
%D0%BF%D0%BF%D0%BF%D0%BF

**Comment by kvichans** [comment]
Можно сильно обобщить - сделать как в "фильтрах шаблонов" в Django!
Для любого макроса `{McrName}` запись `{McrName|func1:par1|func2:par2}` означает, что будет последовательное применение указанных пи-функций, то есть вставляемое значение будет такое
  `str( fun2( fun1( {McrName}, par1 ), par2 ) )`
Тогда то, что вы хотите
`{q}{CurrentWord}` 
будет писаться как 
`{CurrentWord|urllib.quote}`
Нужный для этого `import urllib` можно будет сделать по ходу.

**Comment by Alexey-T** [comment]
мне кажется это менее удобно, чем {q}, т.к. юзеру надо знать что такое urllib, quote.

**Comment by kvichans** [comment]
Даже если вводить новые имена-синонимы, то есть "q"= "urllib.quote", удобнее сделать так {CurrentWord|q}. Конечно нужно будет опубликовать "список сокращений". А _продвинутые_ пользователи смогут применять **любые** функции, не заглядывая в этот список.

**Comment by Alexey-T** [comment]
{CurrentWord|q} вариант тоже конечно нормальный 
не знаю, какие еще есть сокр-ния.
пока мне хватит один |q.

**Comment by kvichans** [comment]
todo

**Comment by kvichans** [comment]
Оказалось, что `quote` находится в другом модуле - в `urllib.parse`.

Вот что не укладывается у меня в голове: `quote('%') == '%25'`
Раз уж % все равно входит в результат, зачем его преобразовывать?
Конечно, руками можно улучшить: `quote('%', safe='%') == '%'`, но это и громозко, и опять порождает _неопределенность_ - какие символы сохранять.

**Comment by Alexey-T** [comment]
IMO, не надо писать safe="%", т.к. надо кодировать процент

**Comment by kvichans** [comment]
ок

**Comment by kvichans** [comment]
Нужно тестировать

**Comment by Alexey-T** [comment]
- создал тул, http://google.com/search?q={CurrentWord}
- вызвал на слове "eeeere"
- гугл выдает ошибку

с таким url- http://google.com/search%3Fq%3Deeeere
- еще баг- второй раз длг настройки Тулов не вызыв., в консоли нет ошибки
  (до рестарта Куд)

**Comment by kvichans** [comment]
Первая проблема понятная - это потому что url сейчас пропускается через quote перед передачей в браузер. Не могу сообразить, что делать
Второй баг - не вижу за что зацепиться.

**Comment by Alexey-T** [comment]
теперь работает.
