### ISSUE TITLE
Dlgs sizes differ

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#96]
диалоги разного размера -

![t1](https://cloud.githubusercontent.com/assets/4154978/19830734/77a91592-9e06-11e6-8aab-ed4d612f6b4d.png)
![t2](https://cloud.githubusercontent.com/assets/4154978/19830735/7ac7f1ee-9e06-11e6-8cb9-bfe4ede6d006.png)

**Comment by kvichans** [comment]
Вроде бы уже про это было. В коде нет причин для различия размеров.

**Comment by Alexey-T** [comment]
В коде DLG_W, DLG_H    = max(WD_LST, ACTS_L[9])+GAP*3, ACTS_T[3]+3#+GAP
  меняется

**Comment by kvichans** [comment]
спасибо - посмотрю

**Comment by kvichans** [comment]
Передайте ваш `exttools.json`
На моем получается одинаково:
`Command.dlg_config:621 DLG_W, DLG_H=(945, 363)`

**Comment by Alexey-T** [comment]
json от Линукс(тоже есть isue)

[exttools.zip](https://github.com/kvichans/cuda_exttools/files/560058/exttools.zip)

**Comment by kvichans** [comment]
Повторил - оказалось, что это от настроек для ширины колонок.
Поправлю
